### ISSUE TITLE
iphone 5 设备，ios10.3.1，点击UITextView 崩溃

### ISSUE THREAD

**Issue by Antduo** [Jacke-xu/WYBasisKit#2]
![image](https://user-images.githubusercontent.com/14332889/51893951-69bb3100-23e1-11e9-8261-12dc0638107c.png)

![image](https://user-images.githubusercontent.com/14332889/51893918-514b1680-23e1-11e9-8d28-7a226f1a7992.png)

**Comment by aiguanren** [comment]
嗯，谢谢亲的反馈，最近比较忙，时间方便了我会进行修改的，您也可以通过邮箱mobileAppDvlp@icloud.com联系我
